version: '3.9'

services:
  dev-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.middlewares=default-headers@file"
      - "traefik.http.routers.api.rule=Host(`dev-api.openmoviedb.com`)"
      - "traefik.http.routers.api.priority=10"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.tls.certresolver=certbot"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
    networks:
      - traefik

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - "${PWD}/.docker/postgres-data:/var/lib/postgresql/data"

networks:
  traefik:
    name: traefik_proxy
    external: true