version: '3.9'

services:
  crdb:
    image: cockroachdb/cockroach:latest
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/.docker/cockroach-data/crdb:/cockroach/cockroach-data"
  
  minio:
    image: minio/minio:latest
    volumes:
      - "${PWD}/.docker/minio/data:/data"
      - "${PWD}/.docker/minio/config:/root/.minio"
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data